### PR TITLE
added flexible column formatting

### LINKED ISSUE #1: flexible table formatting
a superb tool, thanks for open-sourcing!

The issue:
I've added a loop in the sample main around the call to `a`, and noticed, that the table has a fixed width formatting:

```
------+-------+-------+-------+-----+-------------
  min |   avg |   max |     % |   # | scope
------+-------+-------+-------+-----+-------------
 0.00 |  0.00 |  0.00 |  0.00 |   3 | main(sample.cc:26)
 0.00 |  0.00 |  0.00 |  0.00 |   3 |  a(sample.cc:18)
15.82 | 15.82 | 15.82 | 15.82 |  30 |   a(sample.cc:19)
 0.00 |  0.00 |  0.00 |  0.00 |  30 |    b(sample.cc:12)
76.23 | 76.23 | 76.23 | 76.23 | 135 |     b(sample.cc:13)
 0.00 |  0.00 |  0.00 |  0.00 | 135 |      c(sample.cc:6)
192.96 | 192.96 | 192.96 | 192.96 | 360 |       c(sample.cc:8)
```

Some time ago I've been fiddling around with automatic formatting of fixed-width-console outputs: http://ideone.com/k7Jcfy

It's been originally inspired by [bettyprint](https://github.com/dattanchu/bprinter)

Please feel free to dissect and use.

The header coloring placeholder is for a RAII wrapper around [rlutil](https://github.com/tapio/rlutil)

### PR DESCRIPTION
**Pull request by d-led**
closes #1

### CODE REVIEW

**Comment by r-lyeh-archived** [comment]
hey thanks. i just added a missing #include : )

**Comment by r-lyeh-archived** [comment]
btw, vanilla `cl sample.cc profit.cpp` will create an app that crashes at exit now. i cannot figure out where the crash is located at the moment, since adding debug information disables the crash : )

**Comment by r-lyeh-archived** [comment]
nvm figured it out : )

**Comment by d-led** [comment]
:)

**Pull request merged**
